### ISSUE TITLE
Manifest V3について

### ISSUE THREAD

**Issue by pikesaury** [patioglass/questionnaire-youtube#17]
つべアンケ便利に利用させて頂いております。こちらManifest V3についてご予定はありますでしょうか。
ご検討の程よろしくお願いいたします。

**Comment by patioglass** [comment]
@pikesaury 
お問い合わせありがとうございました。

V3の対応をさせていただきました、ストアの方では反映されましたので、インストール済みの場合は順次反映されると思います。
https://chromewebstore.google.com/detail/%E3%81%A4%E3%81%B9%E3%82%A2%E3%83%B3%E3%82%B1/pdiliohipapmhedahgimljfpaimdaapi?hl=ja

アプリの方お使いいただき、ありがとうございます🙇‍♀️
何かまたありましたら気軽に言っていただけると幸いです

**Comment by pikesaury** [comment]
[patioglass](https://github.com/patioglass)様
迅速にご対応頂きまして感謝いたします！引き続きありがたく利用させていただきます！
